name: ss_hospitals
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true


  assets:
    - assets/

  fonts:
    - family: Sans Serif
      fonts:
        - asset: fonts/Tactico.otf

    - family: Raleway
      fonts:
        - asset: fonts/Glamore-lgE7w.otf

    - family: Arial
      fonts:
        - asset: fonts/Georgia Regular font.TTF

    - family: Script
      fonts:
        - asset: fonts/Bellina.ttf


